ansiblePackages:
- name: community-okd
  url: https://galaxy.ansible.com/download/community-okd-2.2.0.tar.gz
- name: kubernetes-core
  url: https://galaxy.ansible.com/download/kubernetes-core-2.3.2.tar.gz
- name: community-vmware
  url: https://galaxy.ansible.com/download/community-vmware-2.9.1.tar.gz
- name: community-crypto
  url: https://galaxy.ansible.com/download/community-crypto-2.7.0.tar.gz
- name: community-general
  url: https://galaxy.ansible.com/download/community-general-5.6.0.tar.gz
- name: ansible-posix
  url: https://galaxy.ansible.com/download/ansible-posix-1.4.0.tar.gz

tools:
- https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.12/openshift-client-linux.tar.gz
- https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable-4.12/oc-mirror.tar.gz
- https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/mirror-registry/1.3.4/mirror-registry.tar.gz

pythonPackages: [ kubernetes==25.3.0, pyvmomi==8.0.0.1.2, openshift==0.13.1, jmespath==1.0.1, dnspython==2.2.1 ]